In [1]:
n= 10 #10 period
r00= 0.05
u=1.1
d=0.9
q=.5
face_value=100.0

In [2]:
import numpy as np
def short_rate_tree(n,r00,u,d):
    tree = np.zeros((n+1,n+1))
    for i in range(n+1):
        for j in range(i+1):
            tree[i][j]=r00*u**j*d**(i-j)
    return tree

In [3]:
short_rate_tree(n,r00,u,d)

array([[0.05      , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.045     , 0.055     , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.0405    , 0.0495    , 0.0605    , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.03645   , 0.04455   , 0.05445   , 0.06655   , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.032805  , 0.040095  , 0.049005  , 0.059895  , 0.073205  ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.0295245 , 0.0360855 , 0.0441045 , 0.0539055 , 0.0658845 ,
        0.0805255 , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.02657205, 0.03247695, 0.03969405, 0.04851495, 0.

In [4]:
a,b=0.01,1.01
a,b

(0.01, 1.01)

In [5]:
2-1/2

1.5

In [6]:
def hazard_rate_tree(a,b,n):
    tree = np.zeros((n+1,n+1))
    for i in range(n):
        for j in range(i+1):
            tree[i,j]= a*b**(j-i/2)
    return tree

In [7]:
hazard_rate_tree(a,b,n)

array([[0.01      , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.00995037, 0.01004988, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.00990099, 0.01      , 0.0101    , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.00985185, 0.00995037, 0.01004988, 0.01015037, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.00980296, 0.00990099, 0.01      , 0.0101    , 0.010201  ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.00975431, 0.00985185, 0.00995037, 0.01004988, 0.01015037,
        0.01025188, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.0097059 , 0.00980296, 0.00990099, 0.01      , 0.

In [13]:
def defaultable_bond_price(a,b,n,r00,u,d,q,face_value,R = 0.2):
    payoff = np.ones((n+1,n+1))*face_value
    rate_tree = short_rate_tree(n,r00,u,d)
    hazard_tree = hazard_rate_tree(a,b,n)
    for i in range(n-1,-1,-1):
        for j in range(i+1):
            payoff[i,j]=(q*(1-hazard_tree[i,j])*payoff[i+1,j+1]+(1-q)*(1-hazard_tree[i,j])*payoff[i+1,j])/(1+rate_tree[i,j])+ (q*hazard_tree[i,j]*R*face_value+(1-q)*hazard_tree[i,j]*R*face_value)/(1+rate_tree[i,j])
    return payoff

In [14]:
defaultable_bond_price(a,b,n,r00,u,d,q,face_value,R = 0.2)

array([[ 57.21685824, 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        ],
       [ 63.03366138,  57.93139145, 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        ],
       [ 68.59493948,  64.06743792,  59.00264201, 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        ],
       [ 73.83792362,  69.93560612,  65.49626478,  60.51707365,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        ],
       [ 78.71996046,  75.46359102,  71.70525359,  67.41597523,
         62.58655393, 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        ],
       [ 83.21668032,  80.60184532,  77.54654815,  74.00732972,
         69.95035301,  65.35829575, 100. 